name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
  
    - name: Build Docker image with GPU support
      run: |  
              docker buildx create --use
              docker buildx build --platform linux/amd64,linux/arm64 -t your_image_name:latest --gpus all .

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push realcommang/my-jupyter-image:latest
